name: Shadow of the Colossus (Preview Version)
sha1: c4d5576d1cae3721c411a746c7845f5c6f026dbb
options:
    # paths
    basename: SCPS_150.97
    target_path: iso/SCPS_150.97
    base_path: ..
    
    asm_path: asm
    src_path: src
    build_path: build
    
    extensions_path: tools/splat_ext
    symbol_addrs_path: config/symbol_addrs.txt
    undefined_funcs_auto_path: config/undefined_funcs_auto.txt
    undefined_syms_auto_path:  config/undefined_syms_auto.txt
    
    # compiler 
    compiler: EEGCC
    platform: ps2

    #ld_bss_contains_common: True
    ld_bss_is_noload: true

    #migrate_rodata_to_functions: False
    
    #string_encoding: EUC-JP
    rodata_string_guesser_level: 2 # improve string detection
    disasm_unknown: True
    named_regs_for_c_funcs: False
    gp_value: 0x141e70
    find_file_boundaries: False
    section_order: [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
    - [0, databin, elf_header]
    - name: main
      type: code
      start: 0x1000
      vram: 0x100000
      bss_size: 0x301A8
      subalign: 4
      subsegments:
        - [0x1000, asm, sdk/crt0]
        - [0x10d0, asm, os/loadersys]
    ###########
    # Library #
    ###########
        # libkernl.a
        - [0x7cc0, asm, libkernl/klib]
        - [0x8560, asm, libkernl/intr]
        - [0x8868, asm, libkernl/thread]
        - [0xa0f8, asm, libkernl/sifrpc]
        - [0xb1b0, asm, libkernl/filestub]
        - [0xede8, asm, libkernl/iopheap]
        - [0xf338, asm, libkernl/eeloadfile]
        - [0x10098, asm, libkernl/iopreset]
        - [0x10378, asm, libkernl/tlbfunc]
        - [0x108c0, asm, libkernl/tlbtrap]
        - [0x10c20, asm, libkernl/diei]
        - [0x10c88, asm, libkernl/initsys]
        - [0x110b0, asm, libkernl/exit]
        - [0x113b8, asm, libkernl/alarm]
        - [0x11500, asm, libkernl/libtimer]

        - [0x12e50, asm, libkernl/glue]
        - [0x13220, asm, libkernl/deci2]
        - [0x13458, asm, libkernl/tty]
        - [0x139d0, asm, libkernl/sifcmd]
        - [0x14178, asm, libkernl/vifpk025]
        - [0x14188, asm, libkernl/vifpk026]
        - [0x14198, asm, libkernl/vifpk027]
        - [0x141f0, asm, libkernl/vifpk030]
        - [0x14248, asm, libkernl/vifpk036]
        - [0x142a0, asm, libkernl/vifpk039]
        - [0x142f8, asm, libkernl/vifpk040]
        - [0x14328, asm, libkernl/vifpk041]
        - [0x14340, asm, libkernl/vifpk042]
        - [0x143e8, asm, libkernl/vifpk044]
        - [0x14468, asm, libkernl/vifpk053]

        # libgraph.a
        - [0x14490, asm, libgraph/graph001]
        - [0x14630, asm, libgraph/graph002]
        - [0x14698, asm, libgraph/graph006]
        - [0x14880, asm, libgraph/graph008]
        - [0x14968, asm, libgraph/graph009]
        - [0x14c00, asm, libgraph/graph010]
        - [0x14c60, asm, libgraph/graph011]
        - [0x14cf8, asm, libgraph/graph012]
        - [0x15010, asm, libgraph/graph013]
        - [0x15120, asm, libgraph/graph014]
        - [0x15180, asm, libgraph/graph021]
        - [0x152b8, asm, libgraph/graph003]
        - [0x15630, asm, libgraph/graph004]
        - [0x156f0, asm, libgraph/graph005]
        # libdma.a
        - [0x158c0, asm, libdma]
        # libpad2.a
        - [0x16108, asm, libpad2]
        # libvib.a
        - [0x169c0, asm, libvib]
        # libcdvd.a
        - [0x17d58, asm, libcdvd/cdvd000]
        - [0x192d0, asm, libcdvd/cdvd035]

        # libnet.a
        - [0x19480, asm, libnet]

        # libgcc.a
        - [0x24480, asm, libgcc/__divdi3]
        - [0x24B18, asm, libgcc/__moddi3]
        - [0x251A8, asm, libgcc/__udivdi3]
        - [0x25728, asm, libgcc/__umoddi3]
        - [0x25C90, asm, libgcc/__floatdisf]
        - [0x25D78, asm, libgcc/__fixunsdfdi]
        - [0x25E90, asm, libgcc/__fixunssfdi]
        - [0x25fB8, asm, libgcc/__main]

        - [0x263e0, asm, libgcc/_addsub_df]
        - [0x264a0, asm, libgcc/_mul_df]
        - [0x26728, asm, libgcc/_div_df]
        - [0x26868, asm, libgcc/_compare_df]
        - [0x268b8, asm, libgcc/_si_to_df]

        - [0x269a0, asm, libgcc/_df_to_sf]
        - [0x269f8, asm, libgcc/_df_to_usi]
        - [0x271A8, asm, libgcc/frame]
        - [0x28028, asm, libgcc/__muldi3]
        - [0x280A0, asm, libgcc/__floatdidf]
        - [0x28548, asm, libc/abort]
        # libc.a
        - [0x28600, asm, libc/atoi]
        - [0x28868, asm, libc/malloc]
        - [0x28b60, asm, libc/malloc_r]
        - [0x29288, asm, libc/memcmp]
        - [0x2931c, asm, libc/memcpy]
        - [0x294d0, asm, libc/memset]
        - [0x29590, asm, libc/mlock]
        - [0x29660, asm, libc/printf]
        - [0x29730, asm, libc/sbrkr]
        - [0x29788, asm, libc/signal]
        - [0x29a70, asm, libc/signalr]
        - [0x29ae8, asm, libc/sprintf]
        - [0x29c08, asm, libc/sscanf]
        - [0x29CB0, asm, libc/strcat]
        - [0x29DDC, asm, libc/strchr]
        - [0x29F6C, asm, libc/strcmp]
        - [0x2A0B0, asm, libc/strcpy]
        - [0x2A1C4, asm, libc/strlen]
        - [0x2A300, asm, libc/strncmp]
        - [0x2A4B8, asm, libc/strncpy]
        - [0x2A678, asm, libc/strrchr]
        - [0x2A6C8, asm, libc/_strtol_r]
        - [0x2A930, asm, libc/vprintf]
        - [0x2C3b8, asm, libc/vscanf]
        - [0x2D148, asm, libc/vsprintf]

        - [0x2D1F8, asm, libc/swsetup]
        - [0x2D308, asm, libc/atof]
        - [0x2D320, asm, libc/atol]

        - [0x2D570, asm, libc/dtoa]
        - [0x2E7D8, asm, libc/fflush]
        - [0x2E8F0, asm, libc/findfp]
        - [0x2eb90, asm, libc/fread]
        - [0x2f118, asm, libc/fvwrite]
        - [0x2f4f8, asm, libc/fwalk]
        - [0x2f590, asm, libc/locale]
        - [0x2f678, asm, libc/makebuf]

        - [0x30b40, asm, libc/stdio]
        - [0x30cb0, asm, libc/strtod]
        - [0x31c18, asm, libc/strtoul]
        - [0x31e78, asm, libc/ungetc]
        - [0x320e8, asm, libc/writer]

        # libkernl.a
        - [0x32918, asm, libkernl/cache]


        #- [0x32CB4, databin] # .reginfo
        - [0x32D00, data, os/loadersys] # .data
        - [0x371CC, databin] # .ctors
        - [0x371D4, databin] # .dtors
        - [0x371E0, databin] # .eh_frame
        - [0x37200, rodata, os/loadersys]
        - [0x38D88, rodata, libkernl/intr]
        - [0x38DB0, rodata, libkernl/thread]
        - [0x38FA8, rodata, libkernl/sifrpc]
        - [0x38FE0, rodata, libkernl/filestub]
        - [0x39298, rodata, libkernl/eeloadfile]
        - [0x392A0, rodata, libkernl/iopreset]
        - [0x392D0, rodata, libkernl/tlbfunc]
        - [0x39350, rodata, libkernl/initsys]
        - [0x39378, rodata, libkernl/tty]

        - [0x393E8, rodata, libgraph/graph008]
        - [0x39660, rodata, libpad2]
        - [0x396C0, rodata, libvib]
        - [0x39968, rodata, libcdvd/cdvd000]
        - [0x39B98, rodata, libcdvd/cdvd035]
        - [0x39BC0, rodata, libnet]
        - [0x3A550, rodata, libc/strlen]

        - [0x3AE80, rodatabin] # .lit4
        #- [0x3AE84, databin] # .data_nop
        - [0x3AF00, rodatabin] # .sdata
        - [0x3B100, sdata, os/loadersys] 
        - {start: 0x3b300, type: sbss, vram: 0x0013A300, name: sdk/crt0}
        - {start: 0x3b370, type: bss, vram: 0x0013A380, name: sdk/crt0}
    - [0x3B300, databin] # padding
    - [0x3B370, databin] # .shstrtab
    - [0x3B3FC, databin] # ELF section headers
    - [0x3B67C] # end of file
# Section Headers:
#   [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
#   [ 0]                   NULL            00000000 000000 000000 00       0   0 0
#   [ 1] .text             PROGBITS        00100000 001000 031cac 00  AX   0   0 64
#   [ 2] .text_nop         PROGBITS        00131cac 032cac 000008 00  WA   0   0 1
#   [ 3] .reginfo          MIPS_REGINFO    00131cb4 032cb4 000018 01   A   0   0 4
#   [ 4] .data             PROGBITS        00131d00 032d00 0044cc 00  WA   0   0 128
#   [ 5] .ctors            PROGBITS        001361cc 0371cc 000008 00  WA   0   0 4
#   [ 6] .dtors            PROGBITS        001361d4 0371d4 000008 00  WA   0   0 4
#   [ 7] .eh_frame         PROGBITS        001361e0 0371e0 000004 00  WA   0   0 8
#   [ 8] .rodata           PROGBITS        00136200 037200 003c58 00   A   0   0 16
#   [ 9] .lit4             PROGBITS        00139e80 03ae80 000004 00 WAp   0   0 4
#   [10] .data_nop         PROGBITS        00139e84 03ae84 000008 00  WA   0   0 1
#   [11] .sdata            PROGBITS        00139f00 03af00 000384 00 WAp   0   0 8
#   [12] .sbss             NOBITS          0013a300 03b300 000010 00 WAp   0   0 4
#   [13] .bss              NOBITS          0013a380 03b370 030198 00  WA   0   0 128
#   [14] .mdebug.eabi64    PROGBITS        00000000 03b370 000000 00       0   0 1
#   [15] .shstrtab         STRTAB          00000000 03b370 00008b 00       0   0 1