name: Shadow of the Colossus (Preview Version)
sha1: c4d5576d1cae3721c411a746c7845f5c6f026dbb
options:
    # paths
    basename: SCPS_150.97
    target_path: iso/SCPS_150.97
    base_path: ..
    
    asm_path: asm
    src_path: src
    build_path: build
    
    extensions_path: tools/splat_ext
    symbol_addrs_path: config/symbol_addrs.txt

    create_undefined_funcs_auto: True
    undefined_funcs_auto_path: config/undefined_funcs_auto.txt
    create_undefined_syms_auto: True
    undefined_syms_auto_path:  config/undefined_syms_auto.txt
    
    # compiler 
    compiler: EEGCC
    platform: ps2

    ld_bss_contains_common: True
    ld_bss_is_noload: true

    migrate_rodata_to_functions: True
    use_gp_rel_macro_nonmatching: False
    
    string_encoding: EUC-JP
    rodata_string_guesser_level: 2 # improve string detection
    disasm_unknown: True
    named_regs_for_c_funcs: True
    gp_value: 0x141e70
    find_file_boundaries: False
    section_order: [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
    - [0, databin, elf_header]
    - name: main
      type: code
      start: 0x1000
      vram: 0x100000
      bss_size: 0x301A8
      subalign: null
      subsegments:
        - [0x1000, asm, sdk/crt0]
        - [0x10d0, c, os/loaderSys, "-O3"]
        - [0x2ec0, c, os/loaderSys2]
        - [0x5090, c, os/netSys]
        - [0x5cc0, c, os/padSys]
        - [0x5f58, c, os/powerOff]
        - [0x60b8, c, os/usbSerialSys]
        - [0x6408, c, os/putString, "-O3"]

        # what the hell
        - [0x7c8c, asm, sdk/padding]
    #################
    # SDK Libraries #
    #################
        # libkernl.a
        - [0x7cc0, asm, sdk/libkernl/klib]
        - [0x8560, asm, sdk/libkernl/intr]
        - [0x8790, asm, sdk/libkernl/thread]

        - [0x9f08, asm, sdk/libkernl/kprintf2]
        - [0xa0f8, asm, sdk/libkernl/sifrpc]
        - [0xb1b0, asm, sdk/libkernl/filestub]
        - [0xede8, asm, sdk/libkernl/iopheap]
        - [0xf338, asm, sdk/libkernl/eeloadfile]
        - [0x10098, asm, sdk/libkernl/iopreset]
        - [0x10378, asm, sdk/libkernl/tlbfunc]
        - [0x108c0, asm, sdk/libkernl/tlbtrap]
        - [0x10c20, asm, sdk/libkernl/diei]
        - [0x10c88, asm, sdk/libkernl/initsys]
        - [0x110b0, asm, sdk/libkernl/exit]
        - [0x11350, asm, sdk/libkernl/alarm]
        - [0x11490, asm, sdk/libkernl/timer]
        - [0x12800, asm, sdk/libkernl/alarmtimer]
        - [0x12e50, asm, sdk/libkernl/glue]
        - [0x13220, asm, sdk/libkernl/deci2]
        - [0x13458, asm, sdk/libkernl/tty]
        - [0x139d0, asm, sdk/libkernl/sifcmd]
        - [0x14178, asm, sdk/libkernl/vifpk025]
        - [0x14188, asm, sdk/libkernl/vifpk026]
        - [0x14198, asm, sdk/libkernl/vifpk027]
        - [0x141f0, asm, sdk/libkernl/vifpk030]
        - [0x14248, asm, sdk/libkernl/vifpk036]
        - [0x142a0, asm, sdk/libkernl/vifpk039]
        - [0x142f8, asm, sdk/libkernl/vifpk040]
        - [0x14328, asm, sdk/libkernl/vifpk041]
        - [0x14340, asm, sdk/libkernl/vifpk042]
        - [0x143e8, asm, sdk/libkernl/vifpk044]
        - [0x14468, asm, sdk/libkernl/vifpk053]
        # libgraph.a
        - [0x14490, asm, sdk/libgraph/graph001]
        - [0x14630, asm, sdk/libgraph/graph002]
        - [0x14698, asm, sdk/libgraph/graph006]
        - [0x14880, asm, sdk/libgraph/graph008]
        - [0x14968, asm, sdk/libgraph/graph009]
        - [0x14c00, asm, sdk/libgraph/graph010]
        - [0x14c60, asm, sdk/libgraph/graph011]
        - [0x14cf8, asm, sdk/libgraph/graph012]
        - [0x15010, asm, sdk/libgraph/graph013]
        - [0x15120, asm, sdk/libgraph/graph014]
        - [0x15180, asm, sdk/libgraph/graph021]
        - [0x152b8, asm, sdk/libgraph/graph003]
        - [0x15630, asm, sdk/libgraph/graph004]
        - [0x156f0, asm, sdk/libgraph/graph005]
        # libdma.a
        - [0x158c0, asm, sdk/libdma]
        # libpad2.a
        - [0x16108, asm, sdk/libpad2]
        # libvib.a
        - [0x169c0, asm, sdk/libvib]
        # libdbc.a
        - [0x16b88, asm, sdk/libdbc]
        # libcdvd.a
        - [0x17d58, asm, sdk/libcdvd/cdvd000]
        - [0x192d0, asm, sdk/libcdvd/cdvd035]
        - [0x19458, asm, sdk/libcdvd/cdvd036]
        # libnet.a
        - [0x19480, asm, sdk/libnet]
        # libgcc.a
        - [0x24480, asm, sdk/libgcc/__divdi3]
        - [0x24B18, asm, sdk/libgcc/__moddi3]
        - [0x251A8, asm, sdk/libgcc/__udivdi3]
        - [0x25728, asm, sdk/libgcc/__umoddi3]
        - [0x25C90, asm, sdk/libgcc/__floatdisf]
        - [0x25D78, asm, sdk/libgcc/__fixunsdfdi]
        - [0x25E90, asm, sdk/libgcc/__fixunssfdi]
        - [0x25fB8, asm, sdk/libgcc/__main]
        - [0x26140, asm, sdk/libgcc/_sf_to_df]
        - [0x263e0, asm, sdk/libgcc/_addsub_df]
        - [0x264a0, asm, sdk/libgcc/_mul_df]
        - [0x26728, asm, sdk/libgcc/_div_df]
        - [0x26868, asm, sdk/libgcc/_compare_df]
        - [0x268b8, asm, sdk/libgcc/_si_to_df]
        - [0x26970, asm, sdk/libgcc/_make_df]
        - [0x269a0, asm, sdk/libgcc/_df_to_sf]
        - [0x269f8, asm, sdk/libgcc/_df_to_usi]
        - [0x271A8, asm, sdk/libgcc/frame]
        - [0x28028, asm, sdk/libgcc/__muldi3]
        - [0x280A0, asm, sdk/libgcc/__floatdidf]
        - [0x28148, asm, sdk/libgcc/_unpack_sf]
        - [0x281a8, asm, sdk/libgcc/_make_sf]
        - [0x281d8, asm, sdk/libgcc/_pack_df]
        - [0x282b0, asm, sdk/libgcc/_unpack_df]
        - [0x28370, asm, sdk/libgcc/_fpcmp_parts_df]
        - [0x28490, asm, sdk/libgcc/_pack_sf]
        # libc.a
        - [0x28548, asm, sdk/libc/abort]
        - [0x28600, asm, sdk/libc/atoi]
        - [0x28868, asm, sdk/libc/malloc]
        - [0x28b60, asm, sdk/libc/malloc_r]
        - [0x29288, asm, sdk/libc/memcmp]
        - [0x2931c, asm, sdk/libc/memcpy]
        - [0x294d0, asm, sdk/libc/memset]
        - [0x29590, asm, sdk/libc/mlock]
        - [0x29660, asm, sdk/libc/printf]
        - [0x29730, asm, sdk/libc/sbrkr]
        - [0x29788, asm, sdk/libc/signal]
        - [0x29a70, asm, sdk/libc/signalr]
        - [0x29ae8, asm, sdk/libc/sprintf]
        - [0x29c08, asm, sdk/libc/sscanf]
        - [0x29CB0, asm, sdk/libc/strcat]
        - [0x29DDC, asm, sdk/libc/strchr]
        - [0x29F6C, asm, sdk/libc/strcmp]
        - [0x2A0B0, asm, sdk/libc/strcpy]
        - [0x2A1C4, asm, sdk/libc/strlen]
        - [0x2A300, asm, sdk/libc/strncmp]
        - [0x2A4B8, asm, sdk/libc/strncpy]
        - [0x2A678, asm, sdk/libc/strrchr]
        - [0x2A6C8, asm, sdk/libc/_strtol_r]
        - [0x2A930, asm, sdk/libc/vprintf]
        - [0x2C3b8, asm, sdk/libc/vscanf]
        - [0x2D148, asm, sdk/libc/vsprintf]
        - [0x2D1F8, asm, sdk/libc/swsetup]
        - [0x2D308, asm, sdk/libc/atof]
        - [0x2D320, asm, sdk/libc/atol]
        - [0x2D570, asm, sdk/libc/dtoa]
        - [0x2E7D8, asm, sdk/libc/fflush]
        - [0x2E8F0, asm, sdk/libc/findfp]
        - [0x2eb90, asm, sdk/libc/fread]
        - [0x2ecb0, asm, sdk/libc/freer]
        - [0x2f118, asm, sdk/libc/fvwrite]
        - [0x2f4f8, asm, sdk/libc/fwalk]
        - [0x2f590, asm, sdk/libc/locale]
        - [0x2f678, asm, sdk/libc/makebuf]
        - [0x2f7d0, asm, sdk/libc/mbtowc_r]
        - [0x2f804, asm, sdk/libc/memchr]
        - [0x2f8e8, asm, sdk/libc/mprec]
        - [0x30938, asm, sdk/libc/refill]
        - [0x30ab8, asm, sdk/libc/sf_isinf]
        - [0x30b00, asm, sdk/libc/s_isnan]
        - [0x30b40, asm, sdk/libc/stdio]
        - [0x30cb0, asm, sdk/libc/strtod]
        - [0x31c18, asm, sdk/libc/strtoul]
        - [0x31e78, asm, sdk/libc/ungetc]
        - [0x320e8, asm, sdk/libc/writer]
        # libkernl.a
        - [0x32918, asm, sdk/libkernl/cache]
        # libgcc.a
        - [0x32b98, asm, sdk/libgcc/_fixdfdi]
        - [0x32c10, asm, sdk/libgcc/_df_to_si]

        #- [0x32CB4, databin] # .reginfo
        - [0x32D00, .data, os/loaderSys]
        - [0x32E00, data, os/loaderSys2]
        - [0x330a0, data, os/netSys]
        - [0x330d0, .data, os/putString]
        - [0x33370, data, sdk/data] # library data
        - [0x371CC, databin, section/ctors] # .ctors
        - [0x371D4, databin, section/dtors] # .dtors
        - [0x371E0, databin, section/eh_frame] # .eh_frame
        - [0x37200, .rodata, os/loaderSys]
        - [0x37630, .rodata, os/loaderSys2]
        - [0x37ee0, .rodata, os/netSys]
        - [0x384f0, .rodata, os/powerOff]
        - [0x38510, .rodata, os/usbSerialSys] 
        - [0x38540, rodatabin, os/Font]
        - [0x38d40, .rodata, os/putString]
        
        - [0x38D88, rodatabin] # SDK rodata
        - [0x3AE80, .lit4, os/putString] # .lit4
        - [0x3AE84, pad] # .data_nop
        - [0x3AF00, .sdata, os/loaderSys]
        - [0x3AF68, sdata, os/loaderSys2]
        - [0x3b188, sdata, os/netSys]
        - [0x3b218, .sdata, os/powerOff]
        - [0x3b230, .sdata, os/putString]
        - [0x3b284, pad]
        
        - {start: 0x3b300, type: sbss, vram: 0x0013A300, name: os/loaderSys}
        - {start: 0x3b300, type: .sbss, vram: 0x0013A308, name: os/usbSerialSys}
        - {start: 0x3b300, type: sbss, vram: 0x0013A30C, name: sdk}
        - {start: 0x3b370, type: bss, vram: 0x0013A380, name: os/loaderSys}
        - {start: 0x3b370, type: bss, vram: 0x0013D9C0, name: os/padSys}
        - {start: 0x3b370, type: .bss, vram: 0x0013DC40, name: os/powerOff}
        - {start: 0x3b370, type: .bss, vram: 0x0013EC40, name: os/usbSerialSys}
        - {start: 0x3b370, type: .bss, vram: 0x0013ECE0, name: os/putString}
        - {start: 0x3b370, type: bss, vram: 0x00143A10, name: sdk}
    - [0x3B300, databin] # padding
    - [0x3B370, databin] # .shstrtab
    - [0x3B3FC, databin] # ELF section headers
    - [0x3B67C] # end of file
# Section Headers:
#   [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
#   [ 0]                   NULL            00000000 000000 000000 00       0   0 0
#   [ 1] .text             PROGBITS        00100000 001000 031cac 00  AX   0   0 64
#   [ 2] .text_nop         PROGBITS        00131cac 032cac 000008 00  WA   0   0 1
#   [ 3] .reginfo          MIPS_REGINFO    00131cb4 032cb4 000018 01   A   0   0 4
#   [ 4] .data             PROGBITS        00131d00 032d00 0044cc 00  WA   0   0 128
#   [ 5] .ctors            PROGBITS        001361cc 0371cc 000008 00  WA   0   0 4
#   [ 6] .dtors            PROGBITS        001361d4 0371d4 000008 00  WA   0   0 4
#   [ 7] .eh_frame         PROGBITS        001361e0 0371e0 000004 00  WA   0   0 8
#   [ 8] .rodata           PROGBITS        00136200 037200 003c58 00   A   0   0 16
#   [ 9] .lit4             PROGBITS        00139e80 03ae80 000004 00 WAp   0   0 4
#   [10] .data_nop         PROGBITS        00139e84 03ae84 000008 00  WA   0   0 1
#   [11] .sdata            PROGBITS        00139f00 03af00 000384 00 WAp   0   0 8
#   [12] .sbss             NOBITS          0013a300 03b300 000010 00 WAp   0   0 4
#   [13] .bss              NOBITS          0013a380 03b370 030198 00  WA   0   0 128
#   [14] .mdebug.eabi64    PROGBITS        00000000 03b370 000000 00       0   0 1
#   [15] .shstrtab         STRTAB          00000000 03b370 00008b 00       0   0 1