#ifndef EXCEPTDATA_H
#define EXCEPTDATA_H

#include "loaderSys2.h"
#include "common.h"

unk_except_s D_00131E00[14] = {
    {
        0,
        ""
    },
    {
        1,
        "tlb mod exception"
    },
    {
        2,
        "tlb not match exception load or operation"
    },
    {
        3,
        "tlb not match exception store"
    },
    {
        4,
        "address error exception load or operation"
    },
    {
        5,
        "address error exception store"
    },
    {
        6,
        "bus error exception operation"
    },
    {
        7,
        "bus error exception load OR store"
    },
    {
        8,
        "system call exception"
    },
    {
        9,
        "break point exception"
    },
    {
        10,
        "reserve operation exception"
    },
    {
        11,
        "coprocessor unusable exception"
    },
    {
        12,
        "arithmetic overflow exception"
    },
    {
        13,
        "trap exception"
    }
};
unk_except_s D_00131E80[2][32] = {
    {
        {
            0,
            " 0"
        },
        {
            0,
            "at"
        },
        {
            0,
            "v0"
        },
        {
            0,
            "v1"
        },
        {
            0,
            "a0"
        },
        {
            0,
            "a1"
        },
        {
            0,
            "a2"
        },
        {
            0,
            "a3"
        },
        {
            0,
            "t0"
        },
        {
            0,
            "t1"
        },
        {
            0,
            "t2"
        },
        {
            0,
            "t3"
        },
        {
            0,
            "t4"
        },
        {
            0,
            "t5"
        },
        {
            0,
            "t6"
        },
        {
            0,
            "t7"
        },
        {
            0,
            "s0"
        },
        {
            0,
            "s1"
        },
        {
            0,
            "s2"
        },
        {
            0,
            "s3"
        },
        {
            0,
            "s4"
        },
        {
            0,
            "s5"
        },
        {
            0,
            "s6"
        },
        {
            0,
            "s7"
        },
        {
            0,
            "t8"
        },
        {
            0,
            "t9"
        },
        {
            0,
            "k0"
        },
        {
            0,
            "k1"
        },
        {
            0,
            "gp"
        },
        {
            0,
            "sp"
        },
        {
            0,
            "s8"
        },
        {
            0,
            "ra"
        },
    },
    {
        {
            0,
            "index"
        },
        {
            0,
            "random"
        },
        {
            0,
            "entrylo0"
        },
        {
            0,
            "entrylo1"
        },
        {
            0,
            "context"
        },
        {
            0,
            "pagemask"
        },
        {
            0,
            "wired"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "badvaddr"
        },
        {
            0,
            "count"
        },
        {
            0,
            "entryhi"
        },
        {
            0,
            "compare"
        },
        {
            0,
            "status"
        },
        {
            0,
            "cause"
        },
        {
            0,
            "epc"
        },
        {
            0,
            "prid"
        },
        {
            0,
            "config"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "reserved"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "debug"
        },
        {
            0,
            "perf"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "(reserved)"
        },
        {
            0,
            "taglo"
        },
        {
            0,
            "raghi"
        },
        {
            0,
            "errorepc"
        },
        {
            0,
            "(reserved"
        },
    }
};
#endif /* EXCEPTDATA_H */