name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt

      - name: Setup Ninja
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install ninja-build
          sudo apt-get update

      - name: Setup build environment
        run: |
          sudo apt-get install binutils-mips-linux-gnu
          mkdir -p iso
          curl -L -o iso/SCPS_150.97 "${{ secrets.FILE_URL }}"
      - name: Run build script
        run: |
          python configure.py
          ninja
