name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt

      - name: Install compiler
        run: |
            scripts/setup_compiler.sh

      - name: Setup Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

            
      - name: Setup build environment
        run: |
          sudo apt-get install -y binutils-mips-linux-gnu
          mkdir -p iso
          curl -L -o iso/SCPS_150.97 "${{ secrets.FILE_URL }}"

      - name: Run build script
        run: |
          python configure.py
          ninja

      - name: Post to frogress endpoint
        run: |
          python3 scripts/upload_progress.py --frogress_api_key ${{ secrets.FROGRESS_API_KEY }}
