name: Frogress

on:
  push:
    branches:
      - main
      - frogress

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo dpkg --add-architecture i386
          sudo apt-get update

      - name: Setup build environment
        run: |
          sudo apt-get install binutils-mips-linux-gnu
          scripts/setup_ee_gcc_linux.sh
          curl -o disc/SCPS_150.97 "${{ secrets.FILE_URL }}"

      - name: Run build script
        run: |
          python configure.py
          ninja

      - name: Post to frogress endpoint
        run: |
          python3 scripts/upload_progress.py --frogress_api_key ${{ secrets.FROGRESS_API_KEY }}
